import errorHandler from "@/helpers/error";
import Product from "@/models/product";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  const search = request.nextUrl.searchParams.get("search") as string;
  console.log("ðŸš€ ~ GET ~ search:", search);
  const page = request.nextUrl.searchParams.get("page") as string;
  console.log("ðŸš€ ~ GET ~ page:", page);
  const limit = request.nextUrl.searchParams.get("limit") as string;
  console.log("ðŸš€ ~ GET ~ limit:", limit);
  // console.log("ðŸš€ ~ GET ~ search:", search);
  try {
    const { products } = await Product.findAll(
      search,
      Number(page),
      Number(limit),
    );
    return NextResponse.json({ products }, { status: 200 });
  } catch (error) {
    console.log("ðŸš€ ~ GET ~ error:", error);
    return errorHandler(error);
  }
}
